# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

CPPPATH = [os.path.join(cwd, 'include')]
objs   += DefineGroup('DeviceDrivers', [], depend = [], CPPPATH = CPPPATH)

Return('objs')
