#-*- encoding: utf-8 -*-
#-------------------------------------------------------------------------------
# RT-Thread RuiChing
# 
# COPYRIGHT (C) 2024-2025 Shanghai Real-Thread Electronic Technology Co., Ltd.
# All rights reserved.
# 
# The license and distribution terms for this file may be
# found in the file LICENSE in this distribution.
#-------------------------------------------------------------------------------
from building import *

group = []

if not GetDepend(['']):
    Return('group')

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']

src = ['hwtimer.c']

if GetDepend(['RT_HWTIMER_ARM_ARCH']):
    src += ['hwtimer-arm_arch.c']

group = DefineGroup('DeviceDrivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
