#-*- encoding: utf-8 -*-
#---------------------------------------------------------------------------------
# RT-Thread Secure
# Copyright (c) 2021, Shanghai Real-Thread Electronic Technology Co., Ltd.
# All rights reserved.
#---------------------------------------------------------------------------------
import os
from building import *
Import('RTT_ROOT')
Import('rtconfig')

#---------------------------------------------------------------------------------
# Package configuration
#---------------------------------------------------------------------------------
PKGNAME = "rt_perf"
DEPENDS = ["PKG_USING_RT_PERF"]
VERSION = "1.0.0"

#---------------------------------------------------------------------------------
# Compile the configuration
#---------------------------------------------------------------------------------
SOURCES          = ["src/rt_perf.c",
                    "src/rt_perf_thread_jitter.c"]

LOCAL_CPPPATH    = []
LOCAL_CCFLAGS    = ""
LOCAL_ASFLAGS    = ""

CPPPATH          = [os.path.join(GetCurrentDir(), './inc')]

CCFLAGS          = ""
ASFLAGS          = ""

CPPDEFINES       = []
LOCAL_CPPDEFINES = []

LIBS             = []
LIBPATH          = [GetCurrentDir()]

LINKFLAGS        = ""
#---------------------------------------------------------------------------------
# Feature clip configuration, optional
#---------------------------------------------------------------------------------
if GetDepend('RT_PERF_ENABLE_IRQ_LATENCY') == True:
    SOURCES += ['src/rt_perf_irq_latency.c']

#---------------------------------------------------------------------------------
# Compiler platform configuration, optional
#---------------------------------------------------------------------------------

#---------------------------------------------------------------------------------
# System variables
#---------------------------------------------------------------------------------
objs   = []
root   = GetCurrentDir()

#---------------------------------------------------------------------------------
# Sub target
#---------------------------------------------------------------------------------
list = os.listdir(root)
if GetDepend(DEPENDS):
    for d in list:
        path = os.path.join(root, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

#---------------------------------------------------------------------------------
# Main target
#---------------------------------------------------------------------------------
objs += DefineGroup(name = PKGNAME, src = SOURCES, depend = DEPENDS,
                   CPPPATH          = CPPPATH,
                   CCFLAGS          = CCFLAGS,
                   ASFLAGS          = ASFLAGS,
                   LOCAL_CPPPATH    = LOCAL_CPPPATH,
                   LOCAL_CCFLAGS    = LOCAL_CCFLAGS,
                   LOCAL_ASFLAGS    = LOCAL_ASFLAGS,
                   CPPDEFINES       = CPPDEFINES,
                   LOCAL_CPPDEFINES = LOCAL_CPPDEFINES,
                   LIBS             = LIBS,
                   LIBPATH          = LIBPATH,
                   LINKFLAGS        = LINKFLAGS)

Return("objs")
#---------------------------------------------------------------------------------
# End
#---------------------------------------------------------------------------------
